### ISSUE TITLE
ESPHome basic voice assistant

### ISSUE THREAD

**Issue by NonaSuomy** [LilyGO/TTGO-T9-RGB_LED-WM8978#15]
Got this working if anyone is still has this thing:

```yaml
# ESPHome configuration for TTGO T-Audio with voice assistant
esphome:
  name: ttgo-t-audio-voice-assistant
  friendly_name: TTGO T-Audio Voice Assistant
  on_boot:
    priority: 375
    then:
      - lambda: |-
          ESP_LOGI("wm8978_init", "Initializing WM8978 codec with required settings");

          // Initialize I2C for WM8978
          auto i2c = id(i2c_bus);
          
          // WM8978 I2C address is 0x1A
          uint8_t codec_addr = 0x1A;
          
          // Check if WM8978 is present
          bool device_found = false;
          if (i2c->write(codec_addr, nullptr, 0, true) == esphome::i2c::ERROR_OK) {
            device_found = true;
          }
          
          if (!device_found) {
            ESP_LOGE("WM8978", "WM8978 not found at address 0x%02X", codec_addr);
            return;
          }
          
          ESP_LOGD("WM8978", "WM8978 found at address 0x%02X", codec_addr);
          
          // Function to write to WM8978 register
          auto WM8978_Write_Reg = [i2c, codec_addr](uint8_t reg, uint16_t val) -> bool {
            uint8_t data[2];
            data[0] = (reg << 1) | ((val >> 8) & 0x01);
            data[1] = val & 0xFF;
            return i2c->write(codec_addr, data, 2);
          };
          
          // Reset all registers (similar to squeezelite-esp32)
          WM8978_Write_Reg(0, 0);

          // Basic initialization sequence (similar to squeezelite-esp32)
          WM8978_Write_Reg(4, 16);   // 16-bit word length, I2S format
          WM8978_Write_Reg(6, 0);    // MCLK as clock source

          // Power management
          WM8978_Write_Reg(1, 0x1B);  // MICEN, BIASEN, VMIDSEL[1:0]=11 (50k)
          WM8978_Write_Reg(2, 0x180); // ROUT1, LOUT1 enable (headphone)
          WM8978_Write_Reg(3, 0x6C);  // LOUT2, ROUT2 enable (speaker), RMIX, LMIX enable
          WM8978_Write_Reg(4, 0x010); // MICBIAS enabled
          // Digital audio path
          WM8978_Write_Reg(10, 8);    // Disable soft mute, 128x oversampling

          // Analog audio path
          WM8978_Write_Reg(43, 16);   // INVROUT2 (speaker phase inversion)

          // Additional settings
          WM8978_Write_Reg(49, 2);    // TSDEN (thermal shutdown enable)

          // Configure EQ to reduce static - THIS IS KEY FOR REDUCING STATIC
          WM8978_Write_Reg(18, 0x12C | (0x3 << 5) | 8);  // EQ1 - 80Hz (bass): +2dB
          WM8978_Write_Reg(19, 0x2C | (0x0 << 5) | 8);   // EQ2 - 230Hz: -4dB (reduce mid-low noise)
          WM8978_Write_Reg(20, 0x2C | (0x0 << 5) | 8);   // EQ3 - 650Hz: -4dB (reduce mid noise)
          WM8978_Write_Reg(21, 0x2C | (0x3 << 5) | 4);   // EQ4 - 4.1kHz: +2dB (enhance clarity)
          WM8978_Write_Reg(22, 0x2C | (0x3 << 5) | 8);   // EQ5 - 11.7kHz: +2dB (enhance clarity)

          // Enable DAC
          WM8978_Write_Reg(3, 0x6C | 3);  // Enable DACR & DACL

          // Configure output channels - enable DAC output
          WM8978_Write_Reg(50, 1);  // Left DAC to left mixer
          WM8978_Write_Reg(51, 1);  // Right DAC to right mixer

          // Set volume
          uint8_t vol = 50;  // Default volume
          WM8978_Write_Reg(52, vol);       // Left headphone volume
          WM8978_Write_Reg(53, vol|0x100); // Right headphone volume + update
          WM8978_Write_Reg(54, vol);       // Left speaker volume
          WM8978_Write_Reg(55, vol|0x100); // Right speaker volume + update
          

          // Output volume
          WM8978_Write_Reg(56, 0x17F); // Left output volume = 0dB
          WM8978_Write_Reg(57, 0x17F); // Right output volume = 0dB
          
          // Input mixer
          WM8978_Write_Reg(45, 0x138); // Left input PGA = +24dB
          WM8978_Write_Reg(46, 0x138); // Right input PGA = +24dB
          
          // Input boost
          WM8978_Write_Reg(47, 0x100); // Left ADC = 0dB
          WM8978_Write_Reg(48, 0x100); // Right ADC = 0dB
          
          // Enable microphone inputs
          WM8978_Write_Reg(44, 0x033); // LINPUT1 and RINPUT1 enabled, +20dB boost
          
          // ADC settings
          WM8978_Write_Reg(14, 0x108); // ADC 128x oversampling
          
          // Additional settings from the GitHub repository
          WM8978_Write_Reg(43, 1<<4);  // INVROUT2 inverted, drive speaker
          WM8978_Write_Reg(47, 1<<8);  // PGABOOSTL, left MIC got 20 db
          WM8978_Write_Reg(48, 1<<8);  // PGABOOSTR, right MIC got 20 db
          WM8978_Write_Reg(49, 1<<1);  // TSDEN, open hot protecting
          WM8978_Write_Reg(10, 1<<3);  // SOFTMUTE closed, 128x sample rate, best SNR
          WM8978_Write_Reg(14, 1<<3);  // ADC 128x sample rate
          
          // Open ADC and input channels in a single register write
          WM8978_Write_Reg(2, 0x1F);  // Enable ADCR, ADCL, INPPGAENR, INPPGAENL, ADCOSR128X
          
          // Explicitly set ADC input mixer settings
          WM8978_Write_Reg(43, 0x010);  // Enable INVROUT2 (for speaker)
          

          // Set higher microphone gain for recording
          WM8978_Write_Reg(45, 0x138);  // Left input PGA = +24dB
          WM8978_Write_Reg(46, 0x138);  // Right input PGA = +24dB
          
          // Enable microphone inputs
          WM8978_Write_Reg(44, 0x033);  // LINPUT1 and RINPUT1 enabled, +20dB boost
          
          ESP_LOGI("wm8978_init", "WM8978 initialized with squeezelite settings");
          
          // Enable speaker amplifier
          id(internal_speaker_amp).turn_on();
          ESP_LOGD("WM8978", "Speaker amplifier enabled");

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: recommended
  variant: esp32

# Enable PSRAM for better audio performance
psram:
  mode: quad
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG
  logs:
    i2c: DEBUG
    microphone: DEBUG
    voice_assistant: DEBUG
    media_player: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key005

# Enable OTA updates
ota:
  platform: esphome
  password: !secret ota_pass005

# Enable WiFi
wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password2
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TTGO-Audio-Voice-Combined"
    password: !secret fallbackhotspot005

# Configure I2C for WM8978 codec
i2c:
  id: i2c_bus
  sda: GPIO19
  scl: GPIO18
  scan: true

# Configure I2S for audio
i2s_audio:
  id: i2s_bus
  i2s_lrclk_pin: GPIO25  # WS (Word Select/LRCLK)
  i2s_bclk_pin: GPIO33   # BCK (Bit Clock)
  i2s_mclk_pin: GPIO0    # MCLK (Master Clock)

# Configure microphone
microphone:
  - platform: i2s_audio
    id: asr_mic
    i2s_din_pin: GPIO27  # DIN pin for microphone input
    adc_type: external
    pdm: false
    i2s_audio_id: i2s_bus
    bits_per_sample: 16bit
    sample_rate: 16000
    channel: left
    # Add debug output to see if we're getting audio data
    # on_data:
    #   - lambda: |-
    #       static uint32_t last_log_time = 0;
    #       static uint32_t packet_count = 0;
    #       static int16_t max_amplitude = 0;
          
    #       // Process audio data to find max amplitude
    #       for (size_t i = 0; i < x.size(); i++) {
    #         int16_t amplitude = abs(x[i]);
    #         if (amplitude > max_amplitude) {
    #           max_amplitude = amplitude;
    #         }
    #       }
          
    #       packet_count++;
          
    #       // Log occasionally (every ~5 seconds)
    #       uint32_t now = millis();
    #       if (now - last_log_time > 5000) {
    #         ESP_LOGI("MIC", "Received audio packet: %d samples, max amplitude: %d, total packets: %d", 
    #                 x.size(), max_amplitude, packet_count);
    #         max_amplitude = 0;
    #         last_log_time = now;
    #       }

# Configure speakers
speaker:
  # Hardware speaker output
  - platform: i2s_audio
    id: i2s_audio_speaker
    sample_rate: 48000
    i2s_dout_pin: GPIO26
    bits_per_sample: 16bit
    i2s_audio_id: i2s_bus
    dac_type: external
    channel: stereo
    #timeout: never
    buffer_duration: 100ms

  # Virtual speakers to combine the announcement and media streams together into one output
  - platform: mixer
    id: mixing_speaker
    output_speaker: i2s_audio_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never

  # Virtual speakers to resample each pipelines' audio, if necessary, as the mixer speaker requires the same sample rate
  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

# Configure buttons
binary_sensor:
  - platform: gpio
    name: "Button 3"
    id: center_button
    pin:
      number: GPIO36
      mode: INPUT
      inverted: true
    on_press:
      - logger.log: "Button 3 pressed"
      - if:
          condition:
            voice_assistant.is_running:
          then:
            - voice_assistant.stop:
          else:
            - voice_assistant.start:
  
  - platform: gpio
    name: "Button 4"
    id: mic_button
    pin:
      number: GPIO34
      mode: INPUT
      inverted: true
    on_press:
      - logger.log: "Button 4 pressed - Starting voice assistant"
      - voice_assistant.start:
    on_release:
      - logger.log: "Button 4 released"

# Configure speaker amplifier
switch:
  - platform: gpio
    pin: GPIO21
    id: internal_speaker_amp
    name: "Internal speaker amp"
    restore_mode: ALWAYS_ON

# Configure media player
media_player:
  - platform: speaker
    id: external_media_player
    name: "TTGO T-Audio Speaker"
    internal: False
    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 0.85
    announcement_pipeline:
      speaker: announcement_resampling_speaker
      format: FLAC      # FLAC for better quality
      num_channels: 1   # Mono for announcements
      sample_rate: 48000
    media_pipeline:
      speaker: media_resampling_speaker
      format: FLAC      # FLAC for better quality
      num_channels: 2   # Stereo for media
      sample_rate: 48000

# External components for voice assistant
external_components:
  - source:
      type: git
      url: https://github.com/esphome/home-assistant-voice-pe
      ref: dev
    components:
      - voice_assistant
    refresh: 0s

# Voice assistant configuration
voice_assistant:
  id: va
  microphone: asr_mic
  media_player: external_media_player
  noise_suppression_level: 0  # Disable noise suppression for testing
  auto_gain: 31dBFS
  volume_multiplier: 4.0  # Increase volume multiplier
  on_client_connected:
    - logger.log:
        format: "Voice assistant client connected"
        level: INFO
  on_client_disconnected:
    - voice_assistant.stop:
    - logger.log:
        format: "Voice assistant client disconnected"
        level: INFO
  on_listening:
    - logger.log:
        format: "Voice assistant is listening"
        level: INFO
  on_stt_vad_start:
    - logger.log:
        format: "Voice detected, processing speech"
        level: INFO
  on_stt_vad_end:
    - logger.log:
        format: "Speech processing complete"
        level: INFO
  on_tts_start:
    - logger.log:
        format: "Voice assistant is responding"
        level: INFO
  on_end:
    - logger.log:
        format: "Voice assistant session ended"
        level: INFO
  on_error:
    - logger.log:
        format: "Voice assistant error: %s"
        args: [code]
        level: ERROR

```
